/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pooii.utfpr.memory_game.View;

import javax.transaction.Transactional;
import pooii.utfpr.memory_game.Model.DAO.connectionHibernate;
import pooii.utfpr.memory_game.Model.RN.GenericRN;
import pooii.utfpr.memory_game.Model.VO.Player;

/**
 *
 * @author Matheus_CRF
 */
public class TelaDefineModo extends javax.swing.JFrame {
    private int mousePx, mousePy;
    private Player player;
    
    private TelaDificuldadeSinglePlayer telaDificuldade;
    
    public TelaDefineModo(Player p) {
        initComponents();
        
        this.player = p;
        lblNome.setText(this.player.getNickName());
        
        this.telaDificuldade = new TelaDificuldadeSinglePlayer(player);
    }
    
    public TelaDefineModo() {
        initComponents();
        
        this.telaDificuldade = new TelaDificuldadeSinglePlayer(this.player);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechar = new javax.swing.JLabel();
        lblBarra = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSinglePlayer = new javax.swing.JLabel();
        lblSingleMultiPlayer = new javax.swing.JLabel();
        lblEstatisticas = new javax.swing.JLabel();
        lblRanking = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        getContentPane().add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 20, 20));

        lblBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBarraMouseDragged(evt);
            }
        });
        lblBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBarraMousePressed(evt);
            }
        });
        getContentPane().add(lblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 20));

        lblNome.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, 20));

        lblSinglePlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSinglePlayerMouseClicked(evt);
            }
        });
        getContentPane().add(lblSinglePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 185, 150, 50));

        lblSingleMultiPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSingleMultiPlayerMouseClicked(evt);
            }
        });
        getContentPane().add(lblSingleMultiPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 185, 150, 50));
        getContentPane().add(lblEstatisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, 50));
        getContentPane().add(lblRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 150, 50));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/TelaDefineModo.jpg"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
       connectionHibernate.close();
       System.exit(0);
    }//GEN-LAST:event_lblFecharMouseClicked

    private void lblBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMouseDragged
        int cordenadaX = evt.getXOnScreen();
        int cordenadaY = evt.getYOnScreen();
        
        this.setLocation(cordenadaX-mousePx, cordenadaY-mousePy);
    }//GEN-LAST:event_lblBarraMouseDragged

    private void lblBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMousePressed
      mousePx = evt.getX();
      mousePy = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBarraMousePressed

    private void lblSinglePlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinglePlayerMouseClicked
        this.dispose();
        this.telaDificuldade.setVisible(true);
    }//GEN-LAST:event_lblSinglePlayerMouseClicked

    private void lblSingleMultiPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSingleMultiPlayerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSingleMultiPlayerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDefineModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDefineModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDefineModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDefineModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDefineModo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBarra;
    private javax.swing.JLabel lblEstatisticas;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JLabel lblSingleMultiPlayer;
    private javax.swing.JLabel lblSinglePlayer;
    // End of variables declaration//GEN-END:variables
}
