/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pooii.utfpr.memory_game.View;

/**
 *
 * @author Jece Xavier
 */
public class TelaInicio extends javax.swing.JFrame {
    /*Atrivutos*/
    private boolean logando;
    
    
    /**
     * Creates new form TelaInicio
     */
    public TelaInicio(boolean logando) {
        this.logando = logando;
        
        initComponents();
        
        definirLayout();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNikName = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lblNikName = new javax.swing.JLabel();
        btnAlterarJanela = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblAlterarJanela = new javax.swing.JLabel();
        btnPartidaRapida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblEmail.setFont(new java.awt.Font("Super Mario 256", 0, 18)); // NOI18N
        lblEmail.setText("EmAil:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(40, 150, 100, 19);

        lblTitulo.setFont(new java.awt.Font("Super Mario 256", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("LOgiN Agora!");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(0, 40, 380, 80);

        lblSenha.setFont(new java.awt.Font("Super Mario 256", 0, 18)); // NOI18N
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(40, 200, 100, 19);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(140, 140, 200, 30);
        getContentPane().add(txtNikName);
        txtNikName.setBounds(140, 240, 200, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(140, 190, 200, 30);

        lblNikName.setFont(new java.awt.Font("Super Mario 256", 0, 18)); // NOI18N
        lblNikName.setText("NikName:");
        getContentPane().add(lblNikName);
        lblNikName.setBounds(40, 250, 100, 19);

        btnAlterarJanela.setText("FAZER CADASTRO");
        btnAlterarJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarJanelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterarJanela);
        btnAlterarJanela.setBounds(180, 390, 160, 30);

        btnConfirmar.setText("ENTRAR");
        getContentPane().add(btnConfirmar);
        btnConfirmar.setBounds(30, 290, 310, 50);

        lblAlterarJanela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAlterarJanela.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAlterarJanela.setText("Não tem Cadastro? Faça agora!");
        getContentPane().add(lblAlterarJanela);
        lblAlterarJanela.setBounds(130, 360, 210, 30);

        btnPartidaRapida.setFont(new java.awt.Font("Super Mario 256", 0, 18)); // NOI18N
        btnPartidaRapida.setText("Partida RapidaAAA");
        getContentPane().add(btnPartidaRapida);
        btnPartidaRapida.setBounds(30, 470, 310, 70);

        setSize(new java.awt.Dimension(400, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarJanelaActionPerformed
        this.logando = !this.logando;
        this.definirLayout();
    }//GEN-LAST:event_btnAlterarJanelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio(true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarJanela;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnPartidaRapida;
    private javax.swing.JLabel lblAlterarJanela;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNikName;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNikName;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables

    /*Funcoes*/
    
    private void definirLayout(){
        if(this.logando){
            this.lblTitulo.setText("Login Agora!");
            this.lblNikName.setVisible(Boolean.FALSE);
            this.lblAlterarJanela.setText("Não tem Cadastro? Faça agora!");
            
            this.txtNikName.setVisible(Boolean.FALSE);
            
            this.btnConfirmar.setText("ENTRAR");
            this.btnAlterarJanela.setText("FAZER CADASTRO");
        }else{
            this.lblTitulo.setText("Cadastro Agora!");
            this.lblNikName.setVisible(Boolean.TRUE);
            this.lblAlterarJanela.setText("Já tem Cadastro? Entre agora!");
            
            this.txtNikName.setVisible(Boolean.TRUE);
            
            this.btnConfirmar.setText("CADASTRAR");
            this.btnAlterarJanela.setText("FAZER LOGIN");
        }
        
        this.repaint();
    }

}
